Feature/crud place
Study-with-Mentors/milease-api pull request #1
Opened 2023-09-15 12:40 UTC by ttdat2232

2023-09-15 12:41 UTC, ttdat2232 commented
check lại hộ tao mấy cái Exception

2023-09-15 15:38 UTC, khanhdinh02 commented
Thiếu class để handle exception
https://github.com/Study-with-Mentors/study-with-mentor-back/blob/dev/src/main/java/com/swm/studywithmentor/controller/ApplicationExceptionHandler.java

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/controller/EnumController.java
> +    @GetMapping("/place-status")
`/places/statuses` nha đạt

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/controller/EnumController.java
> +    @GetMapping("/place-status")
số nhiều nữa nha

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/controller/EnumController.java
> +    @GetMapping("/place-status")
mấy cái dưới cũng tương tự

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/controller/EnumController.java
> +        return new ResponseEntity<>(PlaceStatus.values(), HttpStatus.OK);
Optiona: mấy cái chỉ trả về OK thì ko cần phải xài `ResponseEntity` nha mà trả về trực tiếp object luôn

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/controller/PlaceController.java
> +    private final String BASE_URL = "/api/places/";
??? BASE_URL để làm gì

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/controller/PlaceController.java
> +        response.addHeader("location", location.toString());
mục đích của cái này là làm gì vậy

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/model/dto/PageResult.java
> +    private List<T> values;
Thêm current page nữa

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/model/dto/ProvinceDto.java
> +    public void setDistricts(Object o) {
sao lại dùng `Object` thế này

2023-09-16 10:34 UTC, duynguyendu commented on src/main/java/vn/id/milease/mileaseapi/model/entity/BaseEntity.java
> +    @JsonIgnore
phải trả về `version` nha đạt, để nếu update hoặc delete thì có version
với lại có dto riêng mà nên đâu cần `JsonIgnore` trong entity

2023-09-16 10:39 UTC, ttdat2232 commented on src/main/java/vn/id/milease/mileaseapi/model/dto/ProvinceDto.java
> +    public void setDistricts(Object o) {
cái này của Khánh mà lúc push lên không push cùng nên tao tự generate chứ không để ý

2023-09-16 13:53 UTC, khanhdinh02 requested changes

2023-09-16 13:53 UTC, khanhdinh02 commented on src/main/java/vn/id/milease/mileaseapi/controller/PlaceController.java
> +    public ResponseEntity<Void> deletePlace(@RequestParam(name = "id") long id) {
@PathVariable chứ không phải param

2023-09-17 07:56 UTC, merged